SEPARATOR = ";"
CONTENT_SEPARATOR = ","
END = "."
MSG_LENGTH = 1024

GENERIC_MSG = "0"
INSERT_MSG = "1"
BOARD_STATE_MSG = "2"
REQ_GAMES_MSG = "3"
GAME_LIST_MSG = "4"
JOIN_GAME_MSG = "5"
CREATE_GAME_MSG = "6"
CLIENT_DISCONNECT_MSG = "9"
